"""none_values_2

Revision ID: d9a32f411328
Revises: f1d73cfba1ae
Create Date: 2024-07-24 12:36:14.392875

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d9a32f411328"
down_revision: Union[str, None] = "f1d73cfba1ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "favorite_filter",
        "salary_range_min",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "favorite_filter",
        "salary_range_max",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column("vacancy", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("vacancy", "description", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "vacancy",
        "salary_range_min",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "vacancy",
        "salary_range_max",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vacancy",
        "salary_range_max",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "vacancy",
        "salary_range_min",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column("vacancy", "description", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("vacancy", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "favorite_filter",
        "salary_range_max",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "favorite_filter",
        "salary_range_min",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    # ### end Alembic commands ###
