"""temp

Revision ID: b3a5c9c20445
Revises: 540d05d82dae
Create Date: 2024-07-22 13:15:59.343575

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b3a5c9c20445"
down_revision: Union[str, None] = "540d05d82dae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "temp_vacancies",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("salary_range_min", sa.Float(), nullable=False),
        sa.Column("salary_range_max", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("temp_vacancies")
    # ### end Alembic commands ###
