"""nullable city

Revision ID: 143253537f77
Revises: 6a4083d42921
Create Date: 2024-07-24 13:05:13.960405

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "143253537f77"
down_revision: Union[str, None] = "6a4083d42921"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("city", "city", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("city", "city", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
