"""vacancy_time_2

Revision ID: f1d73cfba1ae
Revises: 163254381cbb
Create Date: 2024-07-24 12:34:28.464136

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f1d73cfba1ae"
down_revision: Union[str, None] = "163254381cbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vacancy",
        sa.Column(
            "date_appearance",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "vacancy", sa.Column("date_disappearance", sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vacancy", "date_disappearance")
    op.drop_column("vacancy", "date_appearance")
    # ### end Alembic commands ###
