"""none_values

Revision ID: 163254381cbb
Revises: c9aea1f62eaf
Create Date: 2024-07-22 14:54:45.611087

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "163254381cbb"
down_revision: Union[str, None] = "c9aea1f62eaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("temp_vacancies", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "temp_vacancies", "description", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("temp_vacancies", "link", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("temp_vacancies", "city", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "temp_vacancies",
        "salary_range_min",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "temp_vacancies",
        "salary_range_max",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "temp_vacancies",
        "salary_range_max",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "temp_vacancies",
        "salary_range_min",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column("temp_vacancies", "city", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("temp_vacancies", "link", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "temp_vacancies", "description", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("temp_vacancies", "name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
